name: zorzim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - mesa=2.1.1
  - mesa-geo=0.7.1
  - graph-tool
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - geopandas
  - shapely
  - pyproj
  - solara
  - contextily
  - cytoolz
  - pip


  - pip:
      - pyrosm
      - pymunk
      - adjusttext
      - bezier
      - emoji
      - future
      - kdepy
      - markdown
      - python-rapidjson
      - s2sphere
      - scattertext